
import java.util.Date;
import java.util.Calendar;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VINAY
 */
public class Book extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    Statement stmt=null;
    
    /**
     * Creates new form NewJFrame
     */
    public Book() {
        initComponents();
        proceedBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        srcComboBox = new javax.swing.JComboBox<>();
        desComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        searchFlightsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        proceedBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        uid_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("From");

        jLabel2.setText("To");

        srcComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pune", "Mumbai", "Bangalore", "Delhi", "Kolkata", "Srinagar" }));

        desComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pune", "Mumbai", "Bangalore", "Delhi", "Kolkata", "Srinagar" }));
        desComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        searchFlightsBtn.setText("Search Flights");
        searchFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightsBtnActionPerformed(evt);
            }
        });

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00:00", "10:00:00", "PUNE", "MUMBAI",  new Integer(40), "02:00:00", "3000"},
                {"18:00:00", "20:15:00", "PUNE", "DELHI",  new Integer(40), "02:15:00", "3500"},
                {"04:00:00", "05:30:00", "PUNE", "BANGALORE",  new Integer(50), "01:30:00", "2750"},
                {"11:00:00", "13:30:00", "PUNE", "KOLKATA",  new Integer(65), "02:30:00", "3500"},
                {"13:00:00", "15:10:00", "MUMBAI", "DELHI",  new Integer(36), "02:10:00", "3200"},
                {"09:15:00", "11:00:00", "MUMBAI", "BANGALORE",  new Integer(52), "01:45:00", "3000"},
                {"20:45:00", "23:30:00", "MUMBAI", "KOLKATA",  new Integer(60), "02:45:00", "4000"},
                {"07:25:00", "10:05:00", "DELHI", "BANGALORE",  new Integer(45), "02:40:00", "3500"},
                {"11:30:00", "13:45:00", "DELHI", "KOLKATA",  new Integer(30), "02:15:00", "3300"},
                {"03:00:00", "05:30:00", "BANGALORE", "KOLKATA",  new Integer(58), "02:30:00", "3000"}
            },
            new String [] {
                "DEPARTURE", "ARRIVAL", "SOURCE", "DESTINATION", "AVL_SEATS", "DURATION", "COST"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookingTable.setCellSelectionEnabled(false);
        bookingTable.setRowSelectionAllowed(true);
        bookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingTable);
        bookingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (bookingTable.getColumnModel().getColumnCount() > 0) {
            bookingTable.getColumnModel().getColumn(0).setResizable(false);
            bookingTable.getColumnModel().getColumn(1).setResizable(false);
            bookingTable.getColumnModel().getColumn(2).setResizable(false);
            bookingTable.getColumnModel().getColumn(3).setResizable(false);
            bookingTable.getColumnModel().getColumn(4).setResizable(false);
            bookingTable.getColumnModel().getColumn(5).setResizable(false);
            bookingTable.getColumnModel().getColumn(6).setResizable(false);
        }

        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter usename : ");

        uid_tf.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                uid_tfCaretUpdate(evt);
            }
        });
        uid_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uid_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(srcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(desComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchFlightsBtn)
                        .addGap(367, 367, 367))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(proceedBtn)
                        .addGap(253, 253, 253)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(srcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchFlightsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void desComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desComboBoxActionPerformed

    private void searchFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightsBtnActionPerformed
        // TODO add your handling code here:
        String src = (String) srcComboBox.getSelectedItem();
        String des = (String) desComboBox.getSelectedItem();
        Date d = DateChooser.getDate();
        String date = Integer.toString(1900+d.getYear())+'-'+Integer.toString(d.getMonth()+1)+'-'+Integer.toString(d.getDate());
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/FLIGHT_BOOKING", "root", "1234");
            String query = "SELECT * FROM FLIGHTS WHERE SOURCE='"+src+"' AND DESTINATION='"+des+"';";
            stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            int i=0;
            while (rs.next()) {
                //bookingTable.setValueAt(rs.getString(1), i, 0);
                //bookingTable.setValueAt(rs.getDate(2), i, 1);
                bookingTable.setValueAt(rs.getTime(1), i, 0);
                bookingTable.setValueAt(rs.getTime(2), i, 1);
                bookingTable.setValueAt(rs.getString(3), i, 2);
                bookingTable.setValueAt(rs.getString(4), i, 3);
                bookingTable.setValueAt(rs.getInt(5), i, 4);
                bookingTable.setValueAt(rs.getTime(6), i, 5);
                bookingTable.setValueAt(rs.getInt(7), i, 6);
                i++;
            }
            while(i<10) {
                bookingTable.setValueAt("", i, 0);
                bookingTable.setValueAt("", i, 1);
                bookingTable.setValueAt("", i, 2);
                bookingTable.setValueAt("", i, 3);
                bookingTable.setValueAt("", i, 4);
                bookingTable.setValueAt("", i, 5);
                bookingTable.setValueAt("", i, 6);
                i++;
            }
            
        } catch(Exception e) {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_searchFlightsBtnActionPerformed
int selectedRow = -1;
    private void bookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingTableMouseClicked
        // TODO add your handling code here:
        selectedRow = bookingTable.getSelectedRow();
        //if (selectedRow!=-1)
        //        proceedBtn.setEnabled(true);
        
    }//GEN-LAST:event_bookingTableMouseClicked
public String bookedFid=null;
    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        
        bookedFid = (String) bookingTable.getValueAt(selectedRow, 0);
        int last_BID = 0;
        try {
            String query = "SELECT B_ID FROM BOOKINGS;";
            stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            int i=0;
            rs.last();
            last_BID =  rs.getInt(1);
        } catch(Exception e) {
            System.out.print(e);
        }
        int curr_BID = ++last_BID;
        String u_id = uid_tf.getText();
        int len_padding_zeros = 6 - (Integer.toString(curr_BID)).length();
        String str_curr_BID="";
        for (int i=0; i < len_padding_zeros; i++)
            str_curr_BID+='0';
        str_curr_BID += Integer.toString(curr_BID);
        try {
            String query = "INSERT INTO BOOKINGS VALUES ('"+str_curr_BID+"', '"+u_id+"', '"+bookedFid+"', NULL, NULL, NULL);";
            stmt = (Statement) con.createStatement();
            stmt.execute(query);
        } catch(Exception e) {
            System.out.print(e);
        }       
        //code to switch to new frame here...
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void uid_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uid_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uid_tfActionPerformed

    private void uid_tfCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_uid_tfCaretUpdate
        proceedBtn.setEnabled(true);
    }//GEN-LAST:event_uid_tfCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JTable bookingTable;
    private javax.swing.JComboBox<String> desComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JButton searchFlightsBtn;
    private javax.swing.JComboBox<String> srcComboBox;
    private javax.swing.JTextField uid_tf;
    // End of variables declaration//GEN-END:variables
}
