/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
/**
 *
 * @author VINAY
 */
public class Flist extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    Statement stmt=null;


    /**
     * Creates new form Flist
     */
    public Flist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JButton();
        NTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ATF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MRB = new javax.swing.JRadioButton();
        FRB = new javax.swing.JRadioButton();
        EnterBtn = new javax.swing.JButton();
        UTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(715, 320));
        setPreferredSize(new java.awt.Dimension(715, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 234, 80, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 190, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of Passengers: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 180, 14);
        getContentPane().add(PTF);
        PTF.setBounds(230, 70, 61, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Passenger Name: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 156, 110, 14);

        ConfirmBtn.setText("Confirm");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmBtn);
        ConfirmBtn.setBounds(440, 30, 100, 23);

        NTF.setEnabled(false);
        NTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTFActionPerformed(evt);
            }
        });
        getContentPane().add(NTF);
        NTF.setBounds(140, 150, 157, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 150, 30, 14);

        ATF.setEnabled(false);
        ATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATFActionPerformed(evt);
            }
        });
        getContentPane().add(ATF);
        ATF.setBounds(360, 150, 60, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 160, 80, 14);

        buttonGroup1.add(MRB);
        MRB.setForeground(new java.awt.Color(255, 255, 255));
        MRB.setText("Male");
        MRB.setEnabled(false);
        MRB.setOpaque(false);
        getContentPane().add(MRB);
        MRB.setBounds(540, 150, 90, 23);

        buttonGroup1.add(FRB);
        FRB.setForeground(new java.awt.Color(255, 255, 255));
        FRB.setText("Female");
        FRB.setEnabled(false);
        FRB.setOpaque(false);
        getContentPane().add(FRB);
        FRB.setBounds(540, 190, 100, 23);

        EnterBtn.setText("Enter");
        EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EnterBtn);
        EnterBtn.setBounds(570, 230, 80, 23);
        getContentPane().add(UTF);
        UTF.setBounds(230, 30, 156, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\VINAY\\Desktop\\ultimate.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Book().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    public String user;
    public int seats;
    public int i=0;
    public String pname;
    public int age=0;
    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        // TODO add your handling code here:
        user = UTF.getText();
        seats = Integer.parseInt(PTF.getText());
        NTF.setEnabled(true);
        ATF.setEnabled(true);
        MRB.setEnabled(true);
        FRB.setEnabled(true);
                
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBtnActionPerformed
        // TODO add your handling code here:
            //NTF.setText("");
            //ATF.setText("0");
            //MRB.setSelected(false);
            //FRB.setSelected(false);
            //if(++i<seats)
            pname = NTF.getText();
            age = Integer.parseInt(ATF.getText());
            char gender =0;
            if(MRB.isSelected())
                gender='M';
            if(FRB.isSelected())
                gender='F';
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/FLIGHT_BOOKING", "root", "1234");
            String query = "INSERT INTO PASSENGER VALUES ('"+pname+"','"+age+"','"+user+"','"+gender+"');";
            stmt = (Statement) con.createStatement();
            stmt.execute(query);
            }
            catch(Exception e){
                System.out.println(e);
            }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/FLIGHT_BOOKING", "root", "1234");
            String query = "UPDATE BOOKINGS,FLIGHTS,BOOKED_FLIGHTS SET BOOKED_SEATS= "+seats+",TOTAL_PRICE = (FLIGHTS.PRICE*"+seats+") WHERE BOOKED_FLIGHTS.DEFAULT_F_ID=FLIGHTS.DEFAULT_F_ID AND BOOKED_FLIGHTS.F_ID = BOOKINGS.F_ID;";
            String query2 = "UPDATE FLIGHTS,BOOKED_FLIGHTS,BOOKINGS SET FLIGHTS.AVL_SEATS =FLIGHTS.AVL_SEATS-"+seats+" WHERE FLIGHTS.DEFAULT_F_ID = BOOKED_FLIGHTS.DEFAULT_F_ID AND BOOKED_FLIGHTS.F_ID = BOOKINGS.F_ID;";
            stmt = (Statement) con.createStatement();
            stmt.execute(query);
            stmt.execute(query2);
            con.close();
            }
            catch(Exception e){
                System.out.println(e);
            }
        if(++i<seats)
        {
            NTF.setText("");
            ATF.setText("0");
            MRB.setSelected(false);
            FRB.setSelected(false);
        }
        else
        {    
            new gg().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_EnterBtnActionPerformed

    private void NTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTFActionPerformed

    private void ATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATF;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JButton EnterBtn;
    private javax.swing.JRadioButton FRB;
    private javax.swing.JRadioButton MRB;
    private javax.swing.JTextField NTF;
    private javax.swing.JTextField PTF;
    private javax.swing.JTextField UTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
